#!/bin/bash

if [ ! -d ./build/java ]; then
    mkdir -p ./build/java
fi

javac -cp :./lib/java/* -d build/java src/java/main/*.java src/java/main/inputgen/*.java src/java/main/inputscriptgen/*.java src/java/main/rslt/*.java
