#!/bin/bash

if [ ! -d ./build/java ]; then
    mkdir -p ./build/java
fi
export JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8
javac -cp :./lib/java/*:./lib/java/commons-cli-1.5.0/*  -d build/java src/java/main/*.java src/java/main/inputgen/*.java src/java/main/inputscriptgen/*.java src/java/main/rslt/*.java
